### ISSUE TITLE
Crash when requesting encryption (2)

### ISSUE THREAD

**Issue by friedger** [openintents/notepad#15]
From Google Play reports:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.openintents.notepad/org.openintents.notepad.crypto.EncryptActivity}: java.lang.SecurityException: Permission Denial: starting Intent { act=org.openintents.action.ENCRYPT cmp=org.openintents.safe/.IntentHandler (has extras) } from ProcessRecord{2db7241a 11108:org.openintents.notepad/u0a175} (pid=11108, uid=10175) requires org.openintents.safe.ACCESS_INTENTS
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2378)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2440)
	at android.app.ActivityThread.access$800(ActivityThread.java:162)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5430)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=org.openintents.action.ENCRYPT cmp=org.openintents.safe/.IntentHandler (has extras) } from ProcessRecord{2db7241a 11108:org.openintents.notepad/u0a175} (pid=11108, uid=10175) requires org.openintents.safe.ACCESS_INTENTS
	at android.os.Parcel.readException(Parcel.java:1546)
	at android.os.Parcel.readException(Parcel.java:1499)
	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2492)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1496)
	at android.app.Activity.startActivityForResult(Activity.java:3852)
	at android.app.Activity.startActivityForResult(Activity.java:3813)
	at org.openintents.notepad.crypto.EncryptActivity.onCreate(EncryptActivity.java:131)
	at android.app.Activity.performCreate(Activity.java:6097)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
	... 10 more
```

**Comment by friedger** [comment]
@cragrim Did you install OI Safe before? Or afterwards? Did you use OI Notepad before?
