### ISSUE TITLE
Crash when requesting encryption

### ISSUE THREAD

**Issue by HenryHu** [openintents/notepad#3]
Steps to reproduce on Nexus 7 with 1.4.0.7:
1. create a new note
2. select menu
3. choose "encrypt"
4. a dialog pops up, asking for oi safe
5. rotate the screen

It seems like that when the screen is rotated, the presence of OI Safe is not checked before running it.

The report says that: Unable to instantiate activity null: java.lang.NullPointerException

Stack trace:
W/System.err( 2194): java.lang.NullPointerException
W/System.err( 2194):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1974)
W/System.err( 2194):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
W/System.err( 2194):    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3512)
W/System.err( 2194):    at android.app.ActivityThread.access$700(ActivityThread.java:130)
W/System.err( 2194):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201)
W/System.err( 2194):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 2194):    at android.os.Looper.loop(Looper.java:137)
W/System.err( 2194):    at android.app.ActivityThread.main(ActivityThread.java:4745)
W/System.err( 2194):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 2194):    at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err( 2194):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
W/System.err( 2194):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
W/System.err( 2194):    at dalvik.system.NativeStart.main(Native Method)

**Comment by cragrim** [comment]
Got a new phone and OI notepad keeps crashing for me when attempting to encrypt.

**Comment by friedger** [comment]
@cragrim I think your problem is related to #15
